---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u2545454/public_html/app
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan optimize:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan view:cache
